### ISSUE TITLE
Ice Source Error

### ISSUE THREAD

**Issue by RealFamousGrant** [rakion99/IceSource#5]
It have a directory
and this happens
https://gyazo.com/6c9d5acc9aef61111ba64884abfcc2ad

**Comment by rakion99** [comment]
the fix is simple next time use common sense and use google its free... or learn how to use visual studio, c++ and/or c#
just right click icesource project > click properties > and change Windows Sdk Version to one that you have.
![image](https://user-images.githubusercontent.com/1360084/32977670-c1a7ec3e-cbf7-11e7-8c04-b3d75295ca7f.png)
